### ISSUE TITLE
Move Eloverblik to Azure

### ISSUE THREAD

**Issue by mogensjuul** [Energinet-DataHub/green-energy-hub#150]
## Problem Description
New Product: “The current state of the Eloverblik has focused primarily on infrastructure deployment, establishing the test environment on Azure and preparing the data connection to DH2.0. Existing products/services fail to address is the deployment of the productive environment, Azure insights and a strategy for release and go live. Our product/service will address this gap by maturing our service in Azure during the next PI. 

## Benefit Hypothesis
We believe that by moving to Azure future high costs can be mitigated and a better performance and stability of the portal. Furthermore, DataHubs freedom of choice will be ensured in the future. 

## Acceptance criteria and must have scope
-	Productive environment up and running 
-	Connections [test/production DH2.0] to DataHub are established and the solution is fully tested In Azure
-	Azure insights configured and ready for the first minimal log events
-	Being ready for release and go live

## Objectives and key results
What is the revenue impact on our business? Is there a potential penalty or other adverse consequences if we delay?
Future high costs for hosting Eloverblik in CGI’s hosting environments are mitigated by moving. Sooner or later those costs will have to be paid if switching to Azure won’t be successful. 

## Leading Indicators
As soon as our test environment is up and running and test data are flowing from DH2.0 we’ll see if the solution will work the way we designed it. 

## Non Functional Requirements
-Hybrid connection must be accepted by ENDK, CGI and Sentia

## Stakeholders
-BSJ, DH support

## Timeline
Deadline 01.12.2021
Ressources: CGI, CCOE, MS Fast Track, IT Cyber Defence, MightyDucks (Eloverblik pipelins).

**Comment by MadsThy** [comment]
Lukket grundet forældelse
