### ISSUE TITLE
New front end

### ISSUE THREAD

**Issue by mogensjuul** [Energinet-DataHub/green-energy-hub#151]
## Problem Description
New Product: “The current state of the Eloverblik has focused primarily on getting to market and not on UX. Reasonably created UX-report shows multiple issues with the UX. Thus, customers are misguided when trying to use the product. Existing products/services fail to address the UX. Our product/service will address this gap by creating a new front end.

## Benefit Hypothesis
We believe that by rewriting the front end, a better UX can be gained and UX issues can be mitigated or removed. The wish about a mobilefirst platform can be realized. 

## Acceptance criteria and must have scope
-	Logical front end layout  
-	Mobilefirst
-	Test for the front end must be automized

## Objectives and key results
Increased usability, better front end, mobile friendly and a better UX in general

## Leading Indicators
UX wireframes and user tests

## Non Functional Requirements
/

## Stakeholders
-BSJ, UX’er (MightyDucks), End user testers

## Timeline
Ressources: UX’ers (MightyDucks)

**Comment by stephaniegitha** [comment]
På PI planning har vi aftalt, at der er overlap mellem funktionalitet for Energioprindelse og Eloverblik. Derfor er scope for denne feature følgende: 

- Login på én portal for private kunder
- Tilknytning af målepunkter via CPR
- Visualisering af private kunders forbrug og produktion på time-, dag-, uge-, måneds- og årsniveau
- Hente private kunders forbrugs- og produktionsdata
