### ISSUE TITLE
Migration Control

### ISSUE THREAD

**Issue by mogensjuul** [Energinet-DataHub/green-energy-hub#214]
### Problem Description
After CGI extracts data from an MP, these are stored in a Json file and transferred to DataHub V3 and stored in a Blob store in Azure.
There is a need to make two automatic checks: 

### Benefit Hypothesis
We are then able to control that the content of the migration files is correct and the values is ready for for the import process

### Acceptance criteria and must have scope

AC 1: Create 1 File containing all filenames for controlling all transferred files in 24 hours

Check that the number of files sent by CGI is also stored in the Blob store. T his is done by creating an autojob that makes a list that shows which files have been stored in the Blob store for the past day. The file should show the name and file size of each file. The file must be saved in an agreed location.
The job should run 10 minutes after midnight each day.

AC2:  Selection of 150 random files transferred the day before.
There must be 150 random files of those transferred the day before. These files are transferred and stored in an agreed location. The job should run automatically and should run 10 minutes after midnight each day.

### Objectives and key results
Increased confidence and and part off the requirement for audit. 

### Non Functional Requirements
none

Stakeholders
- Rasmus Juul Holm Christiansen, PBR, ++

### Timeline PI 6
###Ressources: Titans,

**Comment by mogensjuul** [comment]
@tml fjernet fra Titans og flyttet til Art.  @ENDK-RHC  håndterer selvstændigt

**Comment by MadsBloendAndersen** [comment]
@mogensjuul skal denne feature lukkes?
