### ISSUE TITLE
Close button still visible after closing sidebar (delayed animation)

### ISSUE THREAD

**Issue by stephaniegitha** [Energinet-DataHub/green-energy-hub#216]
Animation running when opening/closing the sidebar? -> https://github.com/angular/components/blob/master/src/material/sidenav/drawer-animations.ts

![sidebar-issue.gif](https://images.zenhubusercontent.com/612cb8944df0eb85278b93db/5493cb4f-cebb-4caf-9f4a-ba2d6c14e2cc)

**Comment by frontend-specialisten** [comment]
Not relevant anymore as it's fixed in another issue.
