### ISSUE TITLE
As a datahub actor we want to create and maintain organisations with related roles and users

### ISSUE THREAD

**Issue by mogensjuul** [Energinet-DataHub/green-energy-hub#242]
## Problem Description
Det skal være muligt at oprette og vedligeholde en organisation med korrekt rolle og med tilhørende GUI brugere

### Benefit Hypothesis
We believe that a smooth handling of organisations and related users is vital for creating the correct business processers 
## Acceptance criteria and must have scope
som datahub FAS bruger skal jeg kunne oprette en organisation med rollen netvirksomhed med info om GLN.
som datahub FAS bruger skal jeg kunne tilknytte en bruger til en organisation med rollen administrator

Som organisations administrator skal jeg kunne tilknytte en oprettet GUI bruger til min organisation.
som datahub FAS bruger kan jeg tilknytte en B2B eller GUI bruger til hvilken som helt organisation med rollen administrator eller bruger

Som bruger kan jeg ved oprettelse anmode om at blive tilknyttet en organisation, ved at kunne vælge en eller flere organisationer 
Som organisations administrator skal jeg kunne godkende/afvise anmodninger fra brugere til en egen organisation
som Datahub FAS bruger skal man kunne ændre aktørens GLN-nummer uden konsekvens i andre sammenhænge(GLN nummer må ikke være et nøgle felt). 

som datahub FAS bruger skal jeg kunne se en samlet oversigt på brugere med filtrering på ikke-tilknyttede brugere eller organisationer
som datahub FAS bruger skal jeg udfra ovenstående liste kunne udføre tilknytninger til en eller flere organisationer med rollen administratore eller bruger

## Objectives and key results
What is the revenue impact on our business? Is there a potential penalty or other adverse consequences if we delay?

## Leading Indicators
What is the revenue impact on our business? Is there a potential penalty or other adverse consequences if we delay?

## Stakeholders
Describe who needs to be kept up-to-date about this feauture, included in discussions, or updated along the way. Stakeholders can be both in Product/Engineering, as well as other teams like Customer Success who might want to keep customers updated on the feature.

## Timeline
What's the timeline for this feature, what resources are needed, and what might potentially block this from hitting the projected end date.

**Comment by MadsBloendAndersen** [comment]
@torben will take care of this :)

**Comment by torben** [comment]
Hey @MadsBloendAndersen, maybe you referring to another Torben? I don't know what to do here :)

**Comment by MadsBloendAndersen** [comment]
@torben you are quite right 👍 Im sorry for the inconvenience.

**Comment by mogensjuul** [comment]
@Tm1807 Vil du opdatere med de korrekte features her. og så fjerne denne

**Comment by Tm1807** [comment]
This feature is now replaced with feature #488 (Market parties) and # 487 (DataHub users)
