### ISSUE TITLE
MessageId mangler i response

### ISSUE THREAD

**Issue by jli-energinet** [Energinet-DataHub/green-energy-hub#265]
INC0282734
JLI

En aktør har indmeldt, at der mangler MessageId i svaret, når de sender en given forespørgsel.
I hans eksempel er der tale om en Get request af typen notifypricelist (anmodning om prisliste), men jeg vil tro, at det gælder generelt på tværs af forespørgsler.

Vores dokumentation (dokumentet "CIM XML og CIM JSON webservice interface jan 2022.pdf") indeholder følgende om MessageId i afsnit 2.1.2 HTTP GET:

![MessageId_dok.png](https://images.zenhubusercontent.com/61540f784bc4f1cd6f0a7d7b/69e9e8c8-a6fb-424f-bc06-ecf601d1dc4f)

Man aktøren oplyser, at han ikke får MessageId returneret i svaret:

![image002.png](https://images.zenhubusercontent.com/61540f784bc4f1cd6f0a7d7b/704e058f-52ea-41a1-a9f0-a4f2df17d50d)

**Comment by Tm1807** [comment]
Vi returnerer 'BundleID' i stedet for den korekte 'MessageID'.
Fejlen rettes nu her og forventes i testmiljø kl. 16:00
