### ISSUE TITLE
400 Bad Request uden fejlbesked i fbm. Opret målepunkt

### ISSUE THREAD

**Issue by jli-energinet** [Energinet-DataHub/green-energy-hub#267]
INC0284344
JLI

Aktøren Andel får en 400 Bad Request, når de indsender RequestChangeAccountingPointCharacteristics (opret målepunkt).

Aktøren skriver:

På nedenstående request får vi et 400 – BadRequest, men ingen body som angiver valideringsfejlen.

![95de89851bc28d105402f646464bcb3b.png](https://images.zenhubusercontent.com/61540f784bc4f1cd6f0a7d7b/79bcb053-1cda-4265-bfcf-44da9edaad04)

XML'en som sendes ses nedenfor:

<?xml version="1.0" encoding="UTF-8"?>
<ns0:RequestChangeAccountingPointCharacteristics_MarketDocument xmlns:ns0="urn:ediel.org:structure:requestchangeaccountingpointcharacteristics:0:1">
<ns0:mRID>SAP.KAM290-50000069397378</ns0:mRID>
<ns0:type>E58</ns0:type>
<ns0:process.processType>E02</ns0:process.processType>
<ns0:businessSector.type>23</ns0:businessSector.type>
<ns0:sender_MarketParticipant.mRID codingScheme="A10">5790000705184</ns0:sender_MarketParticipant.mRID>
<ns0:sender_MarketParticipant.marketRole.type>DDM</ns0:sender_MarketParticipant.marketRole.type>
<ns0:receiver_MarketParticipant.mRID codingScheme="A10">5790001330552</ns0:receiver_MarketParticipant.mRID>
<ns0:receiver_MarketParticipant.marketRole.type>DDZ</ns0:receiver_MarketParticipant.marketRole.type>
<ns0:createdDateTime>2022-03-03T08:43:40Z</ns0:createdDateTime>
<ns0:MktActivityRecord>
<ns0:mRID>SAP.KAM290-50000069397379</ns0:mRID>
<ns0:validityStart_DateAndOrTime.dateTime>2021-12-31T23:00:00Z</ns0:validityStart_DateAndOrTime.dateTime>
<ns0:MarketEvaluationPoint>
<ns0:mRID codingScheme="A10">571313181100060128</ns0:mRID>
<ns0:type>E17</ns0:type>
<ns0:settlementMethod>D01</ns0:settlementMethod>
<ns0:meteringMethod>D02</ns0:meteringMethod>
<ns0:connectionState>E22</ns0:connectionState>
<ns0:readCycle>PT1H</ns0:readCycle>
<ns0:netSettlementGroup>6</ns0:netSettlementGroup>
<ns0:meteringGridArea_Domain.mRID codingScheme="NDK">740</ns0:meteringGridArea_Domain.mRID>
<ns0:linked_MarketEvaluationPoint.mRID codingScheme="A10">571313174000715397</ns0:linked_MarketEvaluationPoint.mRID>
<ns0:physicalConnectionCapacity>6</ns0:physicalConnectionCapacity>
<ns0:mPConnectionType>D02</ns0:mPConnectionType>
<ns0:disconnectionMethod>D01</ns0:disconnectionMethod>
<ns0:asset_MktPSRType.psrType>D11</ns0:asset_MktPSRType.psrType>
<ns0:Series>
<ns0:product>8716867000030</ns0:product>
<ns0:quantity_Measure_Unit.name>KWH</ns0:quantity_Measure_Unit.name>
</ns0:Series>
<ns0:usagePointLocation.geoInfoReference>0a3f50ae-7196-32b8-e044-0003ba298018</ns0:usagePointLocation.geoInfoReference>
<ns0:usagePointLocation.mainAddress>
<ns0:streetDetail>
<ns0:code>1460</ns0:code>
<ns0:name>Skafterupvej</ns0:name>
<ns0:number>141</ns0:number>
</ns0:streetDetail>
<ns0:townDetail>
<ns0:code>330</ns0:code>
<ns0:name>Rude</ns0:name>
<ns0:section>Bisserup</ns0:section>
<ns0:country>DK</ns0:country>
</ns0:townDetail>
<ns0:postalCode>4243</ns0:postalCode>
</ns0:usagePointLocation.mainAddress>
<ns0:usagePointLocation.actualAddressIndicator>true</ns0:usagePointLocation.actualAddressIndicator>
</ns0:MarketEvaluationPoint>
</ns0:MktActivityRecord>
</ns0:RequestChangeAccountingPointCharacteristics_MarketDocument>

**Comment by Sondergaard** [comment]
Fejlen ser ud til at opstå da aktøren bruger et xml-namespace prefix der ikke hedder `cim` - [source](https://github.com/Energinet-DataHub/geh-core/blob/421ba980642547a3111f21a319f030014896e881/source/XmlConversion/source/XmlConverter/XmlMapper.cs#L43)

Vi kan ikke umiddelbart forvente at alle aktører benytter cim som prefix, da det ikke er noget vi kan enforce vi vores xml-schema. Koden bør derfor kunne håndtere at vi kan modtage andre prefix.

@jli-energinet - et workaround for aktøren er at de kan bruge et prefix der hedder cim stedet for ns0.

**Comment by Christian-Meyer** [comment]
@jli-energinet  Den er fixet nu. 
Har testet at det virker i b-002. Prøvede at sende et MP ind med det prefix de havde brugt ns0 og det går igennem.

**Comment by jli-energinet** [comment]
Aktøren bekræftede 14/3, at fejlen var løst. Sagen lukkes.
