### ISSUE TITLE
WSDL in XML-service  (synchronous error). INC0285495 (overført af Irene)

### ISSUE THREAD

**Issue by IreneDataHub** [Energinet-DataHub/green-energy-hub#268]
When they deliver messages to DataHub 3.0, thgey receive sometime an error message synchronously (described in the XIM XML and CIM JSON web service document). It can e.g. be a schedule error so that the message can not be persisted. Please see attached an example of such an error.

Is there a WSDL on this message type and what fields will the error message contain?

![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/8f7dce23-23c3-4660-b332-fb02917b791b)

**Comment by mknic** [comment]
@PerTHenriksen this has nothing to do with API Management so I'm not sure we in Mighty Ducks can be helpful in solving this issue. 

@Christian-Meyer @Tm1807 does this issue look familiar to you?

**Comment by PerTHenriksen** [comment]
Efter aftale med Titan får I denne sag

**Comment by Tm1807** [comment]
Der forefindes ikke en WSDL. Beskrivelsen findes i dokumentet 'Web Service Definition'.
Link er her: https://energinet.dk/-/media/DAC4FC8BF0B04259BEEE94240B1D4C77.pdf
