### ISSUE TITLE
Ugyldig XML

### ISSUE THREAD

**Issue by jli-energinet** [Energinet-DataHub/green-energy-hub#269]
INC0285744
JLI

En it-leverandør har indmeldt følgende:

Vi modtager ugyldig XML når vi henter data fra køerne. Der har sneget sig nogle “gnyffer” med i slutningen af dokumentet:

![4748b5201b52c55002fdebdde54bcb8f.png](https://images.zenhubusercontent.com/61540f784bc4f1cd6f0a7d7b/2d94b6f1-d02a-413e-a191-0b377f863ced)

**Comment by Tm1807** [comment]
Test af om JLI får denne meddelelse
