### ISSUE TITLE
Valideringsfejl

### ISSUE THREAD

**Issue by jli-energinet** [Energinet-DataHub/green-energy-hub#273]

**Comment by jli-energinet** [comment]
INC0285744
JLI

It-leverandøren, som tidligere fik ugyldig XML (jf. issue #269), får nu - efter at issue #269 er løst - i stedet en valideringsfejl.
Vil I kigge på dette?

[5182af811b524d5002fdebdde54bcb9c.png](https://images.zenhubusercontent.com/61540f784bc4f1cd6f0a7d7b/c5f47ba6-48cc-42eb-b954-c2444998e415)

**Comment by jli-energinet** [comment]
@Tm1807: Jeg er ikke sikker på, om det er jer, der skal kigge på denne, men vil I starte ud?

**Comment by Tm1807** [comment]
Den oprindelige fejl med 'gnyfferne' er løst fremadrettet.
Den oprindelige meddelelse med 'gnyffer' var dog allerede dannet og gav problemerne ved forsøget på aktør peek/dequeue...
Vi har derfor dequeued meddelelsen manuelt (efter denne sag blev oprettet) og den ligger derfor ikke længere i kø til aktøren.
Problem solved. Hopefully. :-)
