### ISSUE TITLE
Error in Data/time format in outgoing message

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/green-energy-hub#286]
Please notify TML when this is fixed.

Market party recieves chargemessage from DataHub. The message fails in his schemevalidation and is not processed.
We have pinpointed the error to an element in the message that containes date/time format.

To this call is added a screendump where you can see the excact error and what the solution should look like (the red 0's has to be removed)

Outbound message:
<?xml version="1.0" encoding="utf-8"?>
<cim:NotifyPriceList_MarketDocument xmlns:xsi=http://www.w3.org/2001/XMLSchema-instance xmlns:cim="urn:ediel.org:structure:notifypricelist:0:1" xsi:schemaLocation="urn:ediel.org:structure:notifypricelist:0:1 urn-ediel-org-structure-notifypricelist-0-1.xsd">
    <cim:mRID>089b00078fe144b3acdd6a625245f1d7</cim:mRID>
    <cim:type>D12</cim:type>
    <cim:process.processType>D18</cim:process.processType>
    <cim:businessSector.type>23</cim:businessSector.type>
    <cim:sender_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:sender_MarketParticipant.mRID>
    <cim:sender_MarketParticipant.marketRole.type>DDZ</cim:sender_MarketParticipant.marketRole.type>
    <cim:receiver_MarketParticipant.mRID codingScheme="A10">5790000705184</cim:receiver_MarketParticipant.mRID>
    <cim:receiver_MarketParticipant.marketRole.type>DDM</cim:receiver_MarketParticipant.marketRole.type>
    <cim:createdDateTime>2022-03-21T10:27:53Z</cim:createdDateTime>
    <cim:MktActivityRecord>
        <cim:mRID>d03834615b624bed97eddb39dee7cde3</cim:mRID>
        <cim:snapshot_DateAndOrTime.dateTime>2022-03-21T10:26:20Z</cim:snapshot_DateAndOrTime.dateTime>
        <cim:ChargeGroup>
            <cim:ChargeType>
                <cim:chargeTypeOwner_MarketParticipant.mRID codingScheme="A10">8100000000047</cim:chargeTypeOwner_MarketParticipant.mRID>
                <cim:type>D03</cim:type>
                <cim:mRID>ChargeId12</cim:mRID>
                <cim:name>Charge Tariff Hourly Name</cim:name>
                <cim:description>The charge description</cim:description>
                <cim:effectiveDate>2022-07-31T22:00:00Z</cim:effectiveDate>
                <cim:VATPayer>D01</cim:VATPayer>
                <cim:transparentInvoicing>false</cim:transparentInvoicing>
                <cim:taxIndicator>true</cim:taxIndicator>
                <cim:Series_Period>
                    <cim:resolution>PT1H</cim:resolution>
                    <cim:timeInterval>
                        <cim:start>2022-07-31T22:00:00Z</cim:start>
                        <cim:end>2022-08-01T22:00:00Z</cim:end>
                    </cim:timeInterval>
                    <cim:Point>
                        <cim:position>1</cim:position>
                        <cim:price.amount>1.001000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>2</cim:position>
                        <cim:price.amount>2.002000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>3</cim:position>
                        <cim:price.amount>3.003000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>4</cim:position>
                        <cim:price.amount>4.004000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>5</cim:position>
                        <cim:price.amount>5.005000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>6</cim:position>
                        <cim:price.amount>6.006000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>7</cim:position>
                        <cim:price.amount>7.007000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>8</cim:position>
                        <cim:price.amount>8.008000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>9</cim:position>
                        <cim:price.amount>9.009000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>10</cim:position>
                        <cim:price.amount>10.010000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>11</cim:position>
                        <cim:price.amount>11.011000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>12</cim:position>
                        <cim:price.amount>12.012000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>13</cim:position>
                        <cim:price.amount>13.013000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>14</cim:position>
                        <cim:price.amount>14.014000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>15</cim:position>
                        <cim:price.amount>15.015000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>16</cim:position>
                        <cim:price.amount>16.016000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>17</cim:position>
                        <cim:price.amount>17.017000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>18</cim:position>
                        <cim:price.amount>18.018000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>19</cim:position>
                        <cim:price.amount>19.019000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>20</cim:position>
                        <cim:price.amount>20.020000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>21</cim:position>
                        <cim:price.amount>21.021000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>22</cim:position>
                        <cim:price.amount>22.022000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>23</cim:position>
                        <cim:price.amount>23.023000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>24</cim:position>
                        <cim:price.amount>24.024000</cim:price.amount>
                    </cim:Point>
                </cim:Series_Period>
            </cim:ChargeType>
        </cim:ChargeGroup>
    </cim:MktActivityRecord>
</cim:NotifyPriceList_MarketDocument>

![2022-03-23_11-24-37.png](https://images.zenhubusercontent.com/60bdc2fa67611ea75b0f57c0/894971ae-6cb7-4440-b098-6ef36baf743c)

**Comment by prtandrup** [comment]
Showed @PerTHenriksen the fix. Moving ticket to closed.
