### ISSUE TITLE
Exception while executing function: Functions.CreateDefaultChargeLinksReplierEndpoint Result: Failure Exception: System.AggregateException: One or more errors occurred. (An item with the same key...

### ISSUE THREAD

**Issue by x-platformcoder** [Energinet-DataHub/green-energy-hub#290]
### Current Behavior
throws exception when adding reply to sender dictionary

### Logs
[appinsight](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22%3A%220f12dae0-3f9d-46ae-93a7-7091ff0b950d%22%2C%22ResourceGroup%22%3A%22rg-DataHub-SharedResouces-B-002%22%2C%22Name%22%3A%22appi-shared-sharedres-b-002%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F0f12dae0-3f9d-46ae-93a7-7091ff0b950d%252FresourceGroups%252Frg-DataHub-SharedResouces-B-002%252Fproviders%252FMicrosoft.Insights%252Fcomponents%252Fappi-shared-sharedres-b-002%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel/%7B%22eventId%22%3A%22a8c5a8cb-aa99-11ec-997c-2818783220e1%22%2C%22timestamp%22%3A%222022-03-23T11%3A08%3A50.830Z%22%2C%22cacheId%22%3A%22c585bfb5-a033-4770-9747-62550be7af05%22%2C%22eventTable%22%3A%22exceptions%22%2C%22timeContext%22%3A%7B%22durationMs%22%3A259200000%2C%22endTime%22%3A%222022-03-24T11%3A10%3A52.229Z%22%7D%7D)

**Comment by PerTHenriksen** [comment]
PTH. update as bug, to be refined. Mads to be assigned.

**Comment by PerTHenriksen** [comment]
Closed, was a bug not an incident - moved to appropriate repo
