### ISSUE TITLE
Modtager 401 unauthorized efter x antal successfulde beskedhåndteringer

### ISSUE THREAD

**Issue by mknic** [Energinet-DataHub/green-energy-hub#301]
CS0259062

Ved levering af besked på følgende endpoint: /v1.0/cim/requestchangeofsupplier modtages en 401 unauthorized, efter at have kald endpointet successfuldt x antal gange (4-5 gange i følge brugeren)

Vi har gensendt den nye client secret, så det har ikke noget med udløbsdato for secret at gøre, hvilket også giver mening når de første kald er gået godt.

**Comment by PerTHenriksen** [comment]
@mknic vil du sætte et team på? :)
