### ISSUE TITLE
Create new actors in new actor registry in T-001

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/green-energy-hub#379]
There are two actors who existed in the old registry that do not exist in the new.
This means that mandalorian cannot test in T-001.

The issue has occured because we(batman) have switched to the new registry in metering point. 

The following to actors need to be created 

8200000007739 Role DDM in grid 805
8200000007746 Role DDM in grid 806

**Comment by MadsBloendAndersen** [comment]
@Christian-Meyer who is solving this issue? batman or titans?

**Comment by ENDK-RHC** [comment]
Hi

Which organisations belongs the two actors to?

**Comment by MadsBloendAndersen** [comment]
@ENDK-RHC what do you mean by actor? GLN number? Actor name?

**Comment by khatozen** [comment]
The organisations and actors for the grid areas 805 and 806 are created.

**Comment by khatozen** [comment]
The organisations and actors for the grid areas 805 and 806 are created.
