### ISSUE TITLE
Cancelled - Calculate monthly amounts in DKK for production per daily tariff per energy supplier. 

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/green-energy-hub#472]
# Synopsis
As datahub
we want to calculate monthly amounts for production per **daily** tariff per charge owner, per energy supplier per grid area
so we can have these results for the wholesale settlement. 

# Acceptance criteria
- [ ] Given wholesale calculation, when started, Then DataHub must calculate the monthly amounts for the already calculated daily tariff for production metering points per charge owner per energy supplier per grid area.
- [ ]   Given a wholesale calculation, when started, Then the aggregated result is in monthly (P1M) resolution.

**Comment by khatozen** [comment]
Closed as it is a duplicate of story #480
