### ISSUE TITLE
(HUSK ALEX) Calculate monthly amounts in DKK for production per hourly tariff per energy supplier. 

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/green-energy-hub#473]
# Synopsis
As datahub
we want to calculate monthly amounts for production per **hourly** tariff per charge owner, per energy supplier per grid area
so we can have these results for the wholesale settlement. 

# Acceptance criteria
- [ ] Given wholesale calculation, when started, Then DataHub must calculate the monthly amount for the already calculated hourly amount in #475.
- [ ]   Given a wholesale calculation, when started, Then the aggregated result is in monthly (P1M) resolution.

# Tasks

**Comment by khatozen** [comment]
Tested Ok for wholesale fixing batch # "7e9e5f64-12ea-497e-bbef-ae47a2dc222e"
See the test result in the attached excel sheet.

[Test monthly amounts for hourly tariff.xlsx](https://github.com/Energinet-DataHub/green-energy-hub/files/12684649/Test.monthly.amounts.for.hourly.tariff.xlsx)
