### ISSUE TITLE
[Mosaic] Som en aktør vil jeg kunne modtage de resterende beregningsresultater fra en engrosafregning

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/green-energy-hub#482]
Som en aktør
vil jeg kunne modtage de resterende beregningsresultater fra en engrosafregning
Så de kan indgå i min afregning

**Beskrivelse**
Denne feature går ud på at kunne danne de resterende beregningsresultater fra en engrosafregning og gøre det muligt for en aktør at hente resultatet.

**AC'er**
 - [ ] Vi kan udsende resultater for abonnomenter per elleverandør til elleverandør og charge owner
 - [ ] Vi kan udsende resultater for gebyrer per elleverandør til elleverandør og charge owner

**Comment by PSkarregaard** [comment]
@Christian-Meyer , dækker denne også de beregninger, der ikke når frem fra Wholesale til EDI? Jf. Risiko-board
