### ISSUE TITLE
[Mosaic] Som en prisejer vil jeg anmode om engrosafregning

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/green-energy-hub#483]
Som en prisejer
vil jeg kunne anmode om engrosafregning
Så jeg kan modtage det data jeg har behov for. 

**Beskrivelse**

Denne feature går ud på at gøre det muligt for prisejer at anmode om engrosafregning. 

**AC'er**
- [ ] En prisejer kan anmode om engrosafregning.

**Comment by RSIEnerginet** [comment]
@Christian-Meyer Ift. hvad der står på denne opgave, så skal en Netvirksomhed kunne lave en anmodning, dog kun engrosafregning. Men som UI'en er i dag, kan det ikke lade sig gøre. Det er kun disse 3 roller der kan. Iflg. Alexei er det en meget lille rettelse, men de vil ikke lave den før der er nogen "kloge" hoveder der har sagt at det er rigtigt at det skal virke sådan. 

 <img width="1237" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUZ5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2d7375b06365dc55c3dc606d435e43a3b95aa4a7/image.png" alt="image.png" />

**Comment by mogensjuul** [comment]
@cmy
Vi har talt omkring denne her i Einstein
Vi var usikre på begrebet prisejer og om der så sendes de samme informationer.
Prisejer her er
Netvirksomhed
SYO 
Det er vigtigt at påpege at indholdet er afhængig af rollen. Dvs at det e forskelligt for de 2 typer
