### ISSUE TITLE
Health checks

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/green-energy-hub#506]
# synopsis
as a team
we want to ensure that we have sufficient health checks 
so we can ensure that the product is alive

# acceptance criteria
- [ ] New health checks (if any) have been developed
- [ ] Existing health checks has re-designed if needed
- [ ] the work done has been documented in C4

**Comment by BjarkeMeier** [comment]
@MadsBloendAndersen , how about making this a feature and linking all the related stories and possible add references to relevant info like [this miro board](https://miro.com/app/board/uXjVMs1ffGA=/?share_link_id=693928333509)?
Health checks in general spans multiple stories, so it's hard to define what must be done as part of this single story, or when all has been completed.
