### ISSUE TITLE
PM 03: Beregning af energitidsserier

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/green-energy-hub#517]
Som aktør 
kan jeg modtage energi resultater i RSM-014 i vores preprod miljø
Så jeg kan teste kommunikationen med DataHub 3.0

**Beskrivelse**
Denne epic går ud på at understøtte aktørernes behov for at kunne modtage energiberegninger. Dvs. vi skal kunne starte en beregning og aktørerne skal kunne hente resultatet i enten CIM XML CIM JSON eller eBix formatet.
https://miro.com/app/board/uXjVPIa-Jss=/?moveToWidget=3458764555026191114&amp;cot=14

**AC'er**

- [x] Givet at en aktør, når oprettet så bliver der koblet et token eller et certifikat på dem.
- [x] Givet at en aktør, når tilknyttet et token, så har de adgang til systemet
- [x]  Givet en aktør er oprettet b2b når de pinger dh3 endpoint, så får de en 200 OK [Mosaic] 
- [x] Givet einstein har defineret test data (Tidsserier + Målepunkter + priser) når indlæst af mandalorian i guldtabeller, så kan det bruges til at køre en beregning i preprod miljø'et.
- [x] Givet en aggregering eller balance fiksering, når startet og gennemført, så gemmes resultaterne
- [x] Givet en aggregering eller balance fiksering,når afsluttet, så tager beregningen for alle netområder ikke længere end én time
- [x] Givet en aggregering eller balance fiksering når gennemført, så kan EDI hente resultatet og omdanne til beskeder i det format aktørerne ønsker
- [x] Givet en besked, når dannet, så kan aktørerne hente beskeden.
- [x] Givet en aktør, når besked er hentet, så modtager DH en kvittering på modtagelse.

**Comment by MadsBloendAndersen** [comment]
Notes: 
- Databricks telemetry (Logging)
-

**Comment by BjarkeMeier** [comment]
Spørgsmål:
1. Har vi et preprod miljø, når vi går i gang med denne epic? (Hvad hedder det i givet fald?)
2. Hvilke data er der på preprod miljøet?
3. Hvor lang tid må der gå fra en beregning er færdig til aktørerne kan peeke resultaterne?
