### ISSUE TITLE
[Mandalorian] Confidence i korrektheden af vores beregninger [Skyggeafregning]

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/green-energy-hub#541]
Udvikler refinement

**Comment by BjarkeMeier** [comment]
Inspiration til ting, der kunne være relevante at kigge på - bla test cases.

# What to support

DK
- Grid areas merged during calculation period
- Grid area created during calculation period
- Grid area deleted during calculation period

Grid area
- No non-profiled consumption metering points
- No flex consumption metering points
- No production metering points

Metering point period
- Missing time series (patch with quantity=0 and quality=missing)

Exchange
- There may be metering point(s) in one direction but not the other

# Anticipations

- There is always a grid loss responsible


========
Behov for visualisering?
BDD på beregningsresultater?
