### ISSUE TITLE
CLA

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/green-energy-hub#60]
Notes from Anita:

License file – CLA block remove below on End of terms and conditions
Contribution license agreement – to other people contributing.
CLA supporting github? If it is in a Microsoft domain in github – there is a CLA bot – we need to look into this. See link in meeting from JD.
Do we have the CLA text? – Stephen W will find this for us. – general agreements
René is running with this one

We need this before open source as we are distributing code that isn’t us.
THIS IS A SHOWSTOPPER FOR GOING PUBLIC
Apache text use – invidual and cooperate contributor

**Comment by ASQ-EN** [comment]
Done
