### ISSUE TITLE
Vi har defineret hvilken rækkefølge produktmål skal laves i og hvordan det giver mening ift. mindre releases

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/green-energy-hub#610]
Rækkefølgen er de enkelte produktmål prioriteres efter følgende kriterier
1. Bedste udviklings proces så den samlede udvikling for fase 2 er bygget udfra en logisk  sammenhæng og temporære metoder begrænses
2. Højest mulig forretningsværdi på baggrund af indsats (Den traditionelle)
3. Største risiko set både fra både DH3 og aktør perspektiv
4.  

AC:
- Roadmap i Zenhub er opdateret

**Comment by mogensjuul** [comment]
Kan denne her ikke lukkes efter i dag

**Comment by PerLysemose** [comment]
@mknic kan denne lukkes eller stadig aktuel?
