### ISSUE TITLE
Databricks job kan startes vi Databricks Jobs API

### ISSUE THREAD

**Issue by JesperGomes** [Energinet-DataHub/green-energy-hub#623]
## Synopsis
Dette er et skridt på vejen til transition til databricks baseret generering af rapporter.

## Acceptance Criteria
- [x] Databricks jobbet kan startes med et report_id som argument.
- [x] Jobbet fejler hvis report_id mangler
- [x] report_id udskrives i loggen
- [x] Jobbet ignorerer øvrige parametre end report_id

**Comment by BjarkeMeier** [comment]
Jesper skiller de ekstra parametre ud i en ny story på backloggen.

**Comment by cenh-halfspace** [comment]
@jpm-halfspace are the AC's fulfilled?
