### ISSUE TITLE
Databricks job kan danne metering point periods basis data for alle relevante scenarier

### ISSUE THREAD

**Issue by JesperGomes** [Energinet-DataHub/green-energy-hub#624]
## Synopsis
Dette er et skridt på vejen til transition til databricks baseret generering af rapporter.

## Acceptance Criteria
- [ ] Når databricks job startes, så startes det med alle de nødvendige parametre for at der kan genereres metering point period csv'er for alle de nødvendige usecases (forskellige aktører og filopdelinger)
- [ ] Parametre overføres i et format, som er accepteret af både en udvikler fra Raccoons og Mandalorian

**Comment by BjarkeMeier** [comment]
Erstattet af opgaver på de enkelte filer
