### ISSUE TITLE
Databricks job kan danne energi resultater for alle relevante scenarier (wholesale beregninger)

### ISSUE THREAD

**Issue by JesperGomes** [Energinet-DataHub/green-energy-hub#629]
## Synopsis
Dette er et skridt på vejen til transition til databricks baseret generering af rapporter.

## Acceptance Criteria
- [ ] Når databricks job startes, så startes det med alle de nødvendige parametre for at der kan genererer energi-resultat csv'er for alle de nødvendige usecases (forskellige aktører og filopdelinger)
- [ ] Parametre overføres i et format, som er accepteret af både en udvikler fra Raccoons og Mandalorian

**Comment by BjarkeMeier** [comment]
Erstattet af opgaver på de enkelte filer
