### ISSUE TITLE
Afstemme forventninger til strategi for fase 2

### ISSUE THREAD

**Issue by davidspoulsen** [Energinet-DataHub/green-energy-hub#640]
Som PM
Skal jeg have have afgrænset spilleplanen i forhold til aftaler med aktører og markedet
Så jeg kan bygge en leveringsstrategi som giver mest forretningsmæssig værdi for "fase 2" af Datahub 3.0

Deltagere:
Per B. , Mogens, Kristoffer, David, Per L.

Foreslået agenda:
* Aftaler med marked/aktører - Per B.
* Præsenter mulige udviklingsstrategier - Kristoffer
* Hvad ligger fast og hvad er fleksibelt. F.eks. scope, tid, kvalitet, økonomi - Mogens
* Næste skridt

Forventet outcome:
En forventningsafstemning af hvad ledelse og marked/aktører forventer i forhold til leveringsstrategi og deadlines.

**Comment by mogensjuul** [comment]
@PerLysemose Mener at den kan lukkes
