### ISSUE TITLE
Introduktion af business partner nummer i market participants

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/green-energy-hub#643]
# Synopsis: 
Som DataHub bruger
Vil jeg kunne tilføje og administrere business partner numre til markedets deltagere
Så jeg kan sikre, at business partner information er tilgængelig for wholesale beregninger.

# Acceptance criteria:

 - [ ] Business partner nummer er tilgængeligt i market participants-modulet.
 - [ ] Business partner nummer kan anvendes i wholesale beregninger for korrekt fakturering.
 - [ ] Business partner numre er unikke og kan valideres mod eksisterende regler.
 - [ ] Business partner numre skal være en redigerbare felt.
 - [ ] Business partner numre skal være en "valgfri" felt på organisationerne.

# Test considerations

# Product risk analyse

**Comment by khatozen** [comment]
@MadsBloendAndersen du må gerne lukke den story, den er ikke aktuelt mere
