### ISSUE TITLE
Vi samarbejder om produktmål

### ISSUE THREAD

**Issue by davidspoulsen** [Energinet-DataHub/green-energy-hub#645]
- Hvordan sikrer vi samhørighed? Fx fælles kick-off
- Se eksemple fra GDPR for fase 2. Her er features meget præcise i forhold til, hvad det enkelte team skal lukke før produktmålet kan lukkes
- 

Denne dufter meget af proces. Synes vi skal inddrage SMG i dette.

**Comment by PerLysemose** [comment]
Overdraget til SMG
